name: Batch inference run

on:
  schedule:
    - cron: '0 * * * *'  # the cron expression '0 0 * * *' translates to running the workflow at midnight every day./ '0 * * * *' translates to running the workflow every hour

jobs:
  batch-inference:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas scikit-learn==1.3.2 joblib xgboost hopsworks python-dotenv streamlit

      - name: Run batch inference file
        run: python Batch_inference_pipeline.py
        env:
          HOURS: 24
          HOPSWORKS_KEY : ${{ secrets.HOPSWORKS_KEY }}

      - name: Commit and push predictions if any
        run: |
          git config --global user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Automated prediction update $(date +'%Y-%m-%d %H:%M:%S')"
          git push